---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: busser

platforms:
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[travis-chefcookbook-testrepo::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
