---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: "12"

verifier:
  name: busser

platforms:
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[travis-chefcookbook-testrepo::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
